In [1]:
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql import DataFrame
from datetime import datetime, timedelta
spark = SparkSession.builder \
    .appName("fill_account_balance_f") \
    .enableHiveSupport() \
    .getOrCreate()

In [2]:
on_date = '2018-01-01'#форматы

In [3]:
md_account_d = spark.read.parquet("/user/hive/warehouse/ds.db/md_account_d")
ft_balance_f = spark.read.parquet('/user/hive/warehouse/ds.db/ft_balance_f')
dm_account_balance_f = spark.read.parquet('/user/hive/warehouse/dm.db/dm_account_balance_f')
dm_account_turnover_f = spark.read.parquet(f'/user/hive/warehouse/dm.db/dm_account_turnover_f/')
dm_account_turnover_f.show(100)

+----------+-----------------+-----------------+-----------------+-----------------+----------+
|account_rk|    credit_amount|credit_amount_rub|     debet_amount| debet_amount_rub|   on_date|
+----------+-----------------+-----------------+-----------------+-----------------+----------+
|     13619|   26389.41000000|   26389.41000000|   11579.74000000|   11579.74000000|09-01-2018|
|     13630|80020220.76000000|80020220.76000000|78498976.71000000|78498976.71000000|09-01-2018|
|     13631|  909738.98000000|  909738.98000000|  868633.91000000|  868633.91000000|09-01-2018|
|     13632| 3262575.86000000| 3262575.86000000| 3820310.58000000| 3820310.58000000|09-01-2018|
|     13658|   69235.39000000|   69235.39000000|   31966.89000000|   31966.89000000|09-01-2018|
|     13685|  155499.70000000|  155499.70000000|  258141.85000000|  258141.85000000|09-01-2018|
|     13688|   86664.74000000|   86664.74000000|     272.50000000|     272.50000000|09-01-2018|
|     13873|   14956.22000000|   14956.22000000|   33513.35000000|   33513.35000000|09-01-2018|
|     13883|   76771.39000000|   76771.39000000|   58205.40000000|   58205.40000000|09-01-2018|
|     13906|  113539.46000000|  113539.46000000|   77787.52000000|   77787.52000000|09-01-2018|
|     13907|   30324.44000000|   30324.44000000|   94114.13000000|   94114.13000000|09-01-2018|
|     13985| 3973102.26000000| 3973102.26000000| 3804514.45000000| 3804514.45000000|09-01-2018|
|     14043|     411.90000000|     411.90000000|   30343.30000000|   30343.30000000|09-01-2018|
|     14138|  224344.95000000|  224344.95000000|  161131.97000000|  161131.97000000|09-01-2018|
|     14548|   56768.12000000|   56768.12000000|   35324.86000000|   35324.86000000|09-01-2018|
|     15565|   82836.21000000|   82836.21000000|   77354.08000000|   77354.08000000|09-01-2018|
|     17132|  412002.15000000|  412002.15000000|  327204.33000000|  327204.33000000|09-01-2018|
|     17244|  218503.42000000|  218503.42000000|  194188.76000000|  194188.76000000|09-01-2018|
|     17434|  428943.19000000|  428943.19000000|  385520.15000000|  385520.15000000|09-01-2018|
|     17436| 6659524.16000000| 6659524.16000000| 6323317.93000000| 6323317.93000000|09-01-2018|
|     17437|  410260.04000000|  410260.04000000|  338931.21000000|  338931.21000000|09-01-2018|
|     17439|  227313.18000000|  227313.18000000|  236987.40000000|  236987.40000000|09-01-2018|
|     18112|   88067.22000000|   88067.22000000|   83802.51000000|   83802.51000000|09-01-2018|
|     23463|   36873.02000000|   36873.02000000|   78441.61000000|   78441.61000000|09-01-2018|
|     26899|  159982.76000000|  159982.76000000|  185224.27000000|  185224.27000000|09-01-2018|
|     30277| 1259338.69000000| 1259338.69000000| 1126839.07000000| 1126839.07000000|09-01-2018|
|     37051|  970004.24000000|  970004.24000000|  835923.46000000|  835923.46000000|09-01-2018|
|     41529|  217882.64000000|  217882.64000000|  190171.36000000|  190171.36000000|09-01-2018|
|     45865|   34003.62000000|   34003.62000000|   31407.70000000|   31407.70000000|09-01-2018|
|   1235426|  117136.03000000|  117136.03000000|  131232.18000000|  131232.18000000|09-01-2018|
|   1648686|  240737.33000000|  240737.33000000|  191722.22000000|  191722.22000000|09-01-2018|
|   1761691| 7495122.10000000| 7495122.10000000| 7042326.23000000| 7042326.23000000|09-01-2018|
|   1789424|   72512.72000000|   72512.72000000|   14581.98000000|   14581.98000000|09-01-2018|
|   2266430|   66659.86000000|   66659.86000000|   17920.12000000|   17920.12000000|09-01-2018|
|   2639288|  251906.37000000|  251906.37000000|  103389.35000000|  103389.35000000|09-01-2018|
|   2682057|  222555.83000000|  222555.83000000|  235069.27000000|  235069.27000000|09-01-2018|
|   2682058|  319814.10000000|  319814.10000000|  384804.27000000|  384804.27000000|09-01-2018|
|   2718489|   11376.49000000|   11376.49000000|   73918.90000000|   73918.90000000|09-01-2018|
|   4243715|  302163.77000000|  302163.77000000|  269494.43000000|  269494.43000000|09-01-2018|
|   6077138|  294092.74000000|  294092.74000000|  240042.11000000|  240042.11000000|09-01-2018|
|   6093814|  193030.16000000|  193030.16000000|  251191.44000000|  251191.44000000|09-01-2018|
|   8736635| 2581148.30000000| 2581148.30000000| 2061088.05000000| 2061088.05000000|09-01-2018|
|  10006159| 8603401.79000000| 8603401.79000000| 8970898.49000000| 8970898.49000000|09-01-2018|
|  11735819|   69429.40000000|   69429.40000000|   96935.86000000|   96935.86000000|09-01-2018|
|  12048338|  751523.02000000|  751523.02000000|  711573.61000000|  711573.61000000|09-01-2018|
|  15698716| 1650402.12000000| 1650402.12000000| 1903127.50000000| 1903127.50000000|09-01-2018|
|  18880783|  236448.72000000|  236448.72000000|  246136.19000000|  246136.19000000|09-01-2018|
|  34156728|  478444.30000000|  478444.30000000|  450689.55000000|  450689.55000000|09-01-2018|
|  34156914|  440546.65000000|  440546.65000000|  415628.53000000|  415628.53000000|09-01-2018|
|  34157147|  274922.35000000|  274922.35000000|  262323.56000000|  262323.56000000|09-01-2018|
|  34157174|  444884.85000000|  444884.85000000|  360740.53000000|  360740.53000000|09-01-2018|
|  38622964|   11206.40000000|   11206.40000000|   25447.74000000|   25447.74000000|09-01-2018|
|  41413657|   98796.26000000|   98796.26000000|   93168.74000000|   93168.74000000|09-01-2018|
|  46179628|  125366.43000000|  125366.43000000|   19840.01000000|   19840.01000000|09-01-2018|
|  48182547|  404981.35000000|  404981.35000000|  384149.79000000|  384149.79000000|09-01-2018|
|  57223170|   45337.86000000|   45337.86000000|   64758.03000000|   64758.03000000|09-01-2018|
|  61214401|   57506.98000000|   57506.98000000|   48587.39000000|   48587.39000000|09-01-2018|
|  61214435|   24428.83000000|   24428.83000000|   85879.13000000|   85879.13000000|09-01-2018|
|  67230335|  178368.62000000|  178368.62000000|   90736.55000000|   90736.55000000|09-01-2018|
|  67230420|   66810.54000000|   66810.54000000|   72191.80000000|   72191.80000000|09-01-2018|
|  67304576|  204720.97000000|  204720.97000000|  249723.98000000|  249723.98000000|09-01-2018|
|  68423997|   59139.39000000|   59139.39000000|   12354.85000000|   12354.85000000|09-01-2018|
|  73311876|  226560.46000000|  226560.46000000|  213167.60000000|  213167.60000000|09-01-2018|
|  92629528|  751842.90000000|  751842.90000000|  629506.00000000|  629506.00000000|09-01-2018|
| 127503341|   87418.39000000|   87418.39000000|   22404.93000000|   22404.93000000|09-01-2018|
| 168169085|  356982.05000000|  356982.05000000|  402290.63000000|  402290.63000000|09-01-2018|
| 247574036|  153081.83000000|  153081.83000000|  106062.03000000|  106062.03000000|09-01-2018|
| 303427410|   33096.05000000|   33096.05000000|   64744.53000000|   64744.53000000|09-01-2018|
| 305763419|  125501.31000000|  125501.31000000|   53619.74000000|   53619.74000000|09-01-2018|
| 311159924| 1283296.59000000| 1283296.59000000|  985459.96000000|  985459.96000000|09-01-2018|
| 311161119|    8059.96000000|    8059.96000000|   94202.90000000|   94202.90000000|09-01-2018|
| 311161410|  127471.39000000|  127471.39000000|  131489.82000000|  131489.82000000|09-01-2018|
| 311161686|  348065.37000000|  348065.37000000|  464117.28000000|  464117.28000000|09-01-2018|
| 311161703|  426935.95000000|  426935.95000000|  451442.32000000|  451442.32000000|09-01-2018|
| 312741916|  112024.25000000|  112024.25000000|  190042.34000000|  190042.34000000|09-01-2018|
| 324116366|   43448.36000000|   43448.36000000|   59402.93000000|   59402.93000000|09-01-2018|
| 331483502|   83774.77000000|   83774.77000000|   38550.23000000|   38550.23000000|09-01-2018|
| 393059420|   38626.92000000|   38626.92000000|   56123.42000000|   56123.42000000|09-01-2018|
| 393059422|   96674.98000000|   96674.98000000|   39334.56000000|   39334.56000000|09-01-2018|
| 393806608|  447876.52000000|  447876.52000000|  377832.03000000|  377832.03000000|09-01-2018|
| 393807930|   62104.16000000|   62104.16000000|   35550.53000000|   35550.53000000|09-01-2018|
| 393808409| 7333400.20000000| 7333400.20000000| 7402881.57000000| 7402881.57000000|09-01-2018|
| 397263841|   50080.10000000|   50080.10000000|   25311.37000000|   25311.37000000|09-01-2018|
| 406275750|   46752.59000000|   46752.59000000|   67717.74000000|   67717.74000000|09-01-2018|
| 409684153|   25844.92000000|   25844.92000000|   54182.44000000|   54182.44000000|09-01-2018|
| 409684249|  108893.02000000|  108893.02000000|  115256.78000000|  115256.78000000|09-01-2018|
| 409684688|  525613.17000000|  525613.17000000|  543281.47000000|  543281.47000000|09-01-2018|
| 409685020| 7513660.51000000| 7513660.51000000| 8384677.11000000| 8384677.11000000|09-01-2018|
| 409685106|  172208.66000000|  172208.66000000|  154281.40000000|  154281.40000000|09-01-2018|
| 419005832|   29613.38000000|   29613.38000000|   30470.44000000|   30470.44000000|09-01-2018|
| 434141714|  925679.17000000|  925679.17000000|  891498.63000000|  891498.63000000|09-01-2018|
| 451932940|  167314.17000000|  167314.17000000|  181739.61000000|  181739.61000000|09-01-2018|
| 490890699|   52120.04000000|   52120.04000000|   22961.21000000|   22961.21000000|09-01-2018|
| 527445088|   11513.43000000|   11513.43000000|   16020.42000000|   16020.42000000|09-01-2018|
| 528641685|  865010.35000000|  865010.35000000|  771245.85000000|  771245.85000000|09-01-2018|
| 528787381|   93987.59000000|   93987.59000000|   69709.72000000|   69709.72000000|09-01-2018|
| 529371721|   21606.83000000|   21606.83000000|    2959.25000000|    2959.25000000|09-01-2018|
| 529435844|   12280.38000000|   12280.38000000|   86621.28000000|   86621.28000000|09-01-2018|
| 529686622|   82605.85000000|   82605.85000000|   25071.56000000|   25071.56000000|09-01-2018|
| 529686807|   59112.58000000|   59112.58000000|    4773.10000000|    4773.10000000|09-01-2018|
+----------+-----------------+-----------------+-----------------+-----------------+----------+
only showing top 100 rows

In [4]:
md_account_d.show()

+----------------+--------------------+----------+--------------------+---------+-----------+-------------+
|DATA_ACTUAL_DATE|DATA_ACTUAL_END_DATE|ACCOUNT_RK|      ACCOUNT_NUMBER|CHAR_TYPE|CURRENCY_RK|CURRENCY_CODE|
+----------------+--------------------+----------+--------------------+---------+-----------+-------------+
|      2018-01-01|          2018-01-31|  36237725|30425840700000583001|        А|         35|          840|
|      2018-01-01|          2018-01-31|     24656|30114840700000770002|        А|         35|          840|
|      2018-01-01|          2018-01-31|  18849846|30109810500000435003|        П|         34|          643|
|      2018-01-01|          2018-01-31|   1972647|30111810700000908001|        П|         34|          643|
|      2018-01-01|          2018-01-31|  34157174|30424810100000583001|        А|         34|          643|
|      2018-01-01|          2018-01-31|  48829156|30425810700000583002|        А|         34|          643|
|      2018-01-01|          2018-01-31|     13905|30202810900000002001|        А|         34|          643|
|      2018-01-01|          2018-01-31|     17244|30111810900000672001|        П|         34|          643|
|      2018-01-01|          2018-01-31|  34156787|30236826400000009001|        П|         31|          826|
|      2018-01-01|          2018-01-31|     17132|30111810000000666001|        П|         34|          643|
|      2018-01-01|          2018-01-31|     13560|30110810300000008001|        А|         34|          643|
|      2018-01-01|          2018-01-31|     17439|30111810500000438001|        П|         34|          643|
|      2018-01-01|          2018-01-31|     17434|30111810900000051004|        П|         34|          643|
|      2018-01-01|          2018-01-31|     13630|30102810900000002185|        А|         34|          643|
|      2018-01-01|          2018-01-31| 277937699|30221810900000026000|        А|         34|          643|
|      2018-01-01|          2018-01-31|     13906|30114756800000051003|        А|         30|          756|
|      2018-01-01|          2018-01-31|     14136|30220826800838890001|        П|         31|          826|
|      2018-01-01|          2018-01-31|     13904|30204810500000002001|        А|         34|          643|
|      2018-01-01|          2018-01-31|  34157147|30236840000000003001|        П|         35|          840|
|      2018-01-01|          2018-01-31|     14138|30220978800838890001|        П|         44|          978|
+----------------+--------------------+----------+--------------------+---------+-----------+-------------+
only showing top 20 rows

In [5]:
md_exchange_rate_d = spark.read.parquet('/user/hive/warehouse/ds.db/md_exchange_rate_d')
md_exchange_rate_d.show()

+----------------+--------------------+-----------+--------------+------------+
|DATA_ACTUAL_DATE|DATA_ACTUAL_END_DATE|CURRENCY_RK|REDUCED_COURCE|CODE_ISO_NUM|
+----------------+--------------------+-----------+--------------+------------+
|      2016-07-01|          2050-12-31|         38|       31.8884|         974|
|      2018-01-31|          2018-01-31|  427870281|       28.3798|         933|
|      2018-01-31|          2018-01-31|         29|       7.11613|         752|
|      2018-01-31|          2018-01-31|  529511970|       33.0543|         944|
|      2018-01-31|          2018-01-31|         62|       8.87555|         156|
|      2018-01-31|          2018-01-31|  205699733|       2.74512|         203|
|      2018-01-31|          2018-01-31|  205699734|      0.224063|         348|
|      2018-01-31|          2018-01-31|  409611215|       6.37718|         972|
|      2018-01-31|          2018-01-31|         55|     0.0524955|         410|
|      2018-01-31|          2018-01-31|         57|      0.822974|         417|
|      2018-01-31|          2018-01-31|         58|        35.542|         100|
|      2018-01-31|          2018-01-31|         59|       7.19949|         344|
|      2018-01-31|          2018-01-31|         42|        45.499|         124|
|      2018-01-31|          2018-01-31|         43|       9.34034|         208|
|      2018-01-31|          2018-01-31|         44|       69.5424|         978|
|      2018-01-31|          2018-01-31|         50|      0.882968|         356|
|      2018-01-31|          2018-01-31|         37|      0.517551|         392|
|      2018-01-31|          2018-01-31|         39|       45.3371|          36|
|      2018-01-31|          2018-01-31|         40|       7.27223|         578|
|      2018-01-31|          2018-01-31|         41|       2.01041|         980|
+----------------+--------------------+-----------+--------------+------------+
only showing top 20 rows

In [6]:
ruble_exchange_row = md_exchange_rate_d \
    .filter(F.col("CODE_ISO_NUM") == 643) \
    .select("REDUCED_COURCE") \
    .limit(1) \
    .collect()

if ruble_exchange_row:
    ruble_exchange_rate = ruble_exchange_row[0]["REDUCED_COURCE"]
else:
    ruble_exchange_rate = 1.0

In [37]:
# on_date = '2018-01-01'
on_date_obj = datetime.strptime(on_date, '%Y-%m-%d')
prev_date_str = (on_date_obj - timedelta(days=1)).strftime('%Y-%m-%d')

date_as_date = F.to_date(F.lit(on_date), "yyyy-MM-dd")
prev_date = F.date_sub(date_as_date, 1)
prev_date_formatted = F.date_format(prev_date, "dd.MM.yyyy")

dm_account_balance_f.printSchema()

dm_account_balance_f = dm_account_balance_f.where(F.col('on_date') == prev_date_str)\
.select('on_date', 'account_rk', 'balance_out', (F.col('balance_out') * ruble_exchange_rate).alias('balance_out_rub'))

root
 |-- on_date: date (nullable = true)
 |-- account_rk: integer (nullable = true)
 |-- balance_out: decimal(23,8) (nullable = true)
 |-- balance_out_rub: double (nullable = true)

In [31]:
dm_account_balance_f.show()

+-------+----------+-----------+---------------+
|on_date|account_rk|balance_out|balance_out_rub|
+-------+----------+-----------+---------------+
+-------+----------+-----------+---------------+

In [9]:
md_account_d_between_on_date = md_account_d.where(date_as_date.between(F.col("DATA_ACTUAL_DATE"), F.col("DATA_ACTUAL_END_DATE")))

In [10]:
md_account_d_between_on_date.show()

+----------------+--------------------+----------+--------------------+---------+-----------+-------------+
|DATA_ACTUAL_DATE|DATA_ACTUAL_END_DATE|ACCOUNT_RK|      ACCOUNT_NUMBER|CHAR_TYPE|CURRENCY_RK|CURRENCY_CODE|
+----------------+--------------------+----------+--------------------+---------+-----------+-------------+
|      2018-01-01|          2018-01-31|  36237725|30425840700000583001|        А|         35|          840|
|      2018-01-01|          2018-01-31|     24656|30114840700000770002|        А|         35|          840|
|      2018-01-01|          2018-01-31|  18849846|30109810500000435003|        П|         34|          643|
|      2018-01-01|          2018-01-31|   1972647|30111810700000908001|        П|         34|          643|
|      2018-01-01|          2018-01-31|  34157174|30424810100000583001|        А|         34|          643|
|      2018-01-01|          2018-01-31|  48829156|30425810700000583002|        А|         34|          643|
|      2018-01-01|          2018-01-31|     13905|30202810900000002001|        А|         34|          643|
|      2018-01-01|          2018-01-31|     17244|30111810900000672001|        П|         34|          643|
|      2018-01-01|          2018-01-31|  34156787|30236826400000009001|        П|         31|          826|
|      2018-01-01|          2018-01-31|     17132|30111810000000666001|        П|         34|          643|
|      2018-01-01|          2018-01-31|     13560|30110810300000008001|        А|         34|          643|
|      2018-01-01|          2018-01-31|     17439|30111810500000438001|        П|         34|          643|
|      2018-01-01|          2018-01-31|     17434|30111810900000051004|        П|         34|          643|
|      2018-01-01|          2018-01-31|     13630|30102810900000002185|        А|         34|          643|
|      2018-01-01|          2018-01-31| 277937699|30221810900000026000|        А|         34|          643|
|      2018-01-01|          2018-01-31|     13906|30114756800000051003|        А|         30|          756|
|      2018-01-01|          2018-01-31|     14136|30220826800838890001|        П|         31|          826|
|      2018-01-01|          2018-01-31|     13904|30204810500000002001|        А|         34|          643|
|      2018-01-01|          2018-01-31|  34157147|30236840000000003001|        П|         35|          840|
|      2018-01-01|          2018-01-31|     14138|30220978800838890001|        П|         44|          978|
+----------------+--------------------+----------+--------------------+---------+-----------+-------------+
only showing top 20 rows

In [35]:
prev_balances = dm_account_balance_f.filter(
    F.col("on_date") == prev_date
).select("account_rk", "balance_out")
prev_balances.show()

+-------+----------+-----------+---------------+
|on_date|account_rk|balance_out|balance_out_rub|
+-------+----------+-----------+---------------+
+-------+----------+-----------+---------------+

+----------+-----------+
|account_rk|balance_out|
+----------+-----------+
+----------+-----------+

In [12]:
#обороты по счёту
turnovers = dm_account_turnover_f.filter(
    F.col("on_date") == on_date
).select("account_rk", "debet_amount", "credit_amount")
turnovers.show()

+----------+------------+-------------+
|account_rk|debet_amount|credit_amount|
+----------+------------+-------------+
+----------+------------+-------------+

In [13]:
# Добавим остатки (если нет — 0)
accounts = md_account_d_between_on_date \
    .join(prev_balances, on="account_rk", how="left") \
    .withColumn("balance_out", F.coalesce(F.col("balance_out"), F.lit(0.0)))

In [14]:
# Добавим обороты (если нет — 0)
accounts = accounts.join(turnovers, on="account_rk", how="left") \
    .withColumn("debet_amount", F.coalesce(F.col("debet_amount"), F.lit(0.0))) \
    .withColumn("credit_amount", F.coalesce(F.col("credit_amount"), F.lit(0.0)))
accounts.show()

+----------+----------------+--------------------+--------------------+---------+-----------+-------------+-----------+------------+-------------+
|ACCOUNT_RK|DATA_ACTUAL_DATE|DATA_ACTUAL_END_DATE|      ACCOUNT_NUMBER|CHAR_TYPE|CURRENCY_RK|CURRENCY_CODE|balance_out|debet_amount|credit_amount|
+----------+----------------+--------------------+--------------------+---------+-----------+-------------+-----------+------------+-------------+
|  36237725|      2018-01-01|          2018-01-31|30425840700000583001|        А|         35|          840|        0.0|         0.0|          0.0|
|     24656|      2018-01-01|          2018-01-31|30114840700000770002|        А|         35|          840|        0.0|         0.0|          0.0|
|  18849846|      2018-01-01|          2018-01-31|30109810500000435003|        П|         34|          643|        0.0|         0.0|          0.0|
|   1972647|      2018-01-01|          2018-01-31|30111810700000908001|        П|         34|          643|        0.0|         0.0|          0.0|
|  34157174|      2018-01-01|          2018-01-31|30424810100000583001|        А|         34|          643|        0.0|         0.0|          0.0|
|  48829156|      2018-01-01|          2018-01-31|30425810700000583002|        А|         34|          643|        0.0|         0.0|          0.0|
|     13905|      2018-01-01|          2018-01-31|30202810900000002001|        А|         34|          643|        0.0|         0.0|          0.0|
|     17244|      2018-01-01|          2018-01-31|30111810900000672001|        П|         34|          643|        0.0|         0.0|          0.0|
|  34156787|      2018-01-01|          2018-01-31|30236826400000009001|        П|         31|          826|        0.0|         0.0|          0.0|
|     17132|      2018-01-01|          2018-01-31|30111810000000666001|        П|         34|          643|        0.0|         0.0|          0.0|
|     13560|      2018-01-01|          2018-01-31|30110810300000008001|        А|         34|          643|        0.0|         0.0|          0.0|
|     17439|      2018-01-01|          2018-01-31|30111810500000438001|        П|         34|          643|        0.0|         0.0|          0.0|
|     17434|      2018-01-01|          2018-01-31|30111810900000051004|        П|         34|          643|        0.0|         0.0|          0.0|
|     13630|      2018-01-01|          2018-01-31|30102810900000002185|        А|         34|          643|        0.0|         0.0|          0.0|
| 277937699|      2018-01-01|          2018-01-31|30221810900000026000|        А|         34|          643|        0.0|         0.0|          0.0|
|     13906|      2018-01-01|          2018-01-31|30114756800000051003|        А|         30|          756|        0.0|         0.0|          0.0|
|     14136|      2018-01-01|          2018-01-31|30220826800838890001|        П|         31|          826|        0.0|         0.0|          0.0|
|     13904|      2018-01-01|          2018-01-31|30204810500000002001|        А|         34|          643|        0.0|         0.0|          0.0|
|  34157147|      2018-01-01|          2018-01-31|30236840000000003001|        П|         35|          840|        0.0|         0.0|          0.0|
|     14138|      2018-01-01|          2018-01-31|30220978800838890001|        П|         44|          978|        0.0|         0.0|          0.0|
+----------+----------------+--------------------+--------------------+---------+-----------+-------------+-----------+------------+-------------+
only showing top 20 rows

In [15]:
accounts = accounts.withColumn(
    "balance_out_rub",
    F.when(F.col("char_type") == "А",
         F.col("balance_out") + F.col("debet_amount") - F.col("credit_amount")
    ).when(F.col("char_type") == "П",
         F.col("balance_out") - F.col("debet_amount") + F.col("credit_amount")
    ).otherwise(F.col("balance_out"))  # если тип неизвестен
)

In [16]:
accounts.show()

+----------+----------------+--------------------+--------------------+---------+-----------+-------------+-----------+------------+-------------+---------------+
|ACCOUNT_RK|DATA_ACTUAL_DATE|DATA_ACTUAL_END_DATE|      ACCOUNT_NUMBER|CHAR_TYPE|CURRENCY_RK|CURRENCY_CODE|balance_out|debet_amount|credit_amount|balance_out_rub|
+----------+----------------+--------------------+--------------------+---------+-----------+-------------+-----------+------------+-------------+---------------+
|  36237725|      2018-01-01|          2018-01-31|30425840700000583001|        А|         35|          840|        0.0|         0.0|          0.0|            0.0|
|     24656|      2018-01-01|          2018-01-31|30114840700000770002|        А|         35|          840|        0.0|         0.0|          0.0|            0.0|
|  18849846|      2018-01-01|          2018-01-31|30109810500000435003|        П|         34|          643|        0.0|         0.0|          0.0|            0.0|
|   1972647|      2018-01-01|          2018-01-31|30111810700000908001|        П|         34|          643|        0.0|         0.0|          0.0|            0.0|
|  34157174|      2018-01-01|          2018-01-31|30424810100000583001|        А|         34|          643|        0.0|         0.0|          0.0|            0.0|
|  48829156|      2018-01-01|          2018-01-31|30425810700000583002|        А|         34|          643|        0.0|         0.0|          0.0|            0.0|
|     13905|      2018-01-01|          2018-01-31|30202810900000002001|        А|         34|          643|        0.0|         0.0|          0.0|            0.0|
|     17244|      2018-01-01|          2018-01-31|30111810900000672001|        П|         34|          643|        0.0|         0.0|          0.0|            0.0|
|  34156787|      2018-01-01|          2018-01-31|30236826400000009001|        П|         31|          826|        0.0|         0.0|          0.0|            0.0|
|     17132|      2018-01-01|          2018-01-31|30111810000000666001|        П|         34|          643|        0.0|         0.0|          0.0|            0.0|
|     13560|      2018-01-01|          2018-01-31|30110810300000008001|        А|         34|          643|        0.0|         0.0|          0.0|            0.0|
|     17439|      2018-01-01|          2018-01-31|30111810500000438001|        П|         34|          643|        0.0|         0.0|          0.0|            0.0|
|     17434|      2018-01-01|          2018-01-31|30111810900000051004|        П|         34|          643|        0.0|         0.0|          0.0|            0.0|
|     13630|      2018-01-01|          2018-01-31|30102810900000002185|        А|         34|          643|        0.0|         0.0|          0.0|            0.0|
| 277937699|      2018-01-01|          2018-01-31|30221810900000026000|        А|         34|          643|        0.0|         0.0|          0.0|            0.0|
|     13906|      2018-01-01|          2018-01-31|30114756800000051003|        А|         30|          756|        0.0|         0.0|          0.0|            0.0|
|     14136|      2018-01-01|          2018-01-31|30220826800838890001|        П|         31|          826|        0.0|         0.0|          0.0|            0.0|
|     13904|      2018-01-01|          2018-01-31|30204810500000002001|        А|         34|          643|        0.0|         0.0|          0.0|            0.0|
|  34157147|      2018-01-01|          2018-01-31|30236840000000003001|        П|         35|          840|        0.0|         0.0|          0.0|            0.0|
|     14138|      2018-01-01|          2018-01-31|30220978800838890001|        П|         44|          978|        0.0|         0.0|          0.0|            0.0|
+----------+----------------+--------------------+--------------------+---------+-----------+-------------+-----------+------------+-------------+---------------+
only showing top 20 rows

In [17]:
accounts = accounts.select('ACCOUNT_RK', 'balance_out', ('balance_out_rub')).withColumn('on_date', F.lit(date_as_date))

In [18]:
accounts.show()

+----------+-----------+---------------+----------+
|ACCOUNT_RK|balance_out|balance_out_rub|   on_date|
+----------+-----------+---------------+----------+
|  36237725|        0.0|            0.0|2018-01-01|
|     24656|        0.0|            0.0|2018-01-01|
|  18849846|        0.0|            0.0|2018-01-01|
|   1972647|        0.0|            0.0|2018-01-01|
|  34157174|        0.0|            0.0|2018-01-01|
|  48829156|        0.0|            0.0|2018-01-01|
|     13905|        0.0|            0.0|2018-01-01|
|     17244|        0.0|            0.0|2018-01-01|
|  34156787|        0.0|            0.0|2018-01-01|
|     17132|        0.0|            0.0|2018-01-01|
|     13560|        0.0|            0.0|2018-01-01|
|     17439|        0.0|            0.0|2018-01-01|
|     17434|        0.0|            0.0|2018-01-01|
|     13630|        0.0|            0.0|2018-01-01|
| 277937699|        0.0|            0.0|2018-01-01|
|     13906|        0.0|            0.0|2018-01-01|
|     14136|        0.0|            0.0|2018-01-01|
|     13904|        0.0|            0.0|2018-01-01|
|  34157147|        0.0|            0.0|2018-01-01|
|     14138|        0.0|            0.0|2018-01-01|
+----------+-----------+---------------+----------+
only showing top 20 rows

In [19]:

    # Получение курса
    ruble_exchange_row = md_exchange_rate_d \
        .filter(F.col("CODE_ISO_NUM") == 643) \
        .select("REDUCED_COURCE") \
        .limit(1) \
        .collect()
    
    ruble_exchange_rate = ruble_exchange_row[0]["REDUCED_COURCE"] if ruble_exchange_row else 1.0

    # Получение предыдущей даты как строки
    prev_date_str = (datetime.strptime(on_date, "%Y-%m-%d") - timedelta(days=1)).strftime("%d.%m.%Y")

    # Фильтрация по строковым значениям
    dm_account_balance_f = dm_account_balance_f\
        .where(F.col('on_date') == prev_date_str)\
        .select('on_date', 'account_rk', 'balance_out', 
                (F.col('balance_out') * ruble_exchange_rate).alias('balance_out_rub'))

    # md_account_d: фильтрация по актуальности
    md_account_d_between_on_date = md_account_d\
        .where((F.lit(on_date) >= F.col("DATA_ACTUAL_DATE")) & (F.lit(on_date) <= F.col("DATA_ACTUAL_END_DATE")))

    # Остатки на предыдущую дату
    prev_balances = spark.table("dm.dm_account_balance_f") \
    .filter(F.col("on_date") == prev_date_str) \
    .select("account_rk", "balance_out", "balance_out_rub")

    # Обороты за текущую дату
    turnovers = dm_account_turnover_f.filter(F.col("on_date") == on_date)\
        .select("account_rk", "debet_amount", "credit_amount")

    # Счета + остатки
    accounts = md_account_d_between_on_date \
        .join(prev_balances, on="account_rk", how="left") \
        .withColumn("balance_out", F.coalesce(F.col("balance_out"), F.lit(0.0)))

    # Добавляем обороты
    accounts = accounts.join(turnovers, on="account_rk", how="left") \
        .withColumn("debet_amount", F.coalesce(F.col("debet_amount"), F.lit(0.0))) \
        .withColumn("credit_amount", F.coalesce(F.col("credit_amount"), F.lit(0.0)))
    
    # Расчёт рублёвого остатка
    accounts = accounts.withColumn(
        "balance_out_rub",
        F.when(F.col("char_type") == "А",
             F.col("balance_out") + F.col("debet_amount") - F.col("credit_amount")
        ).when(F.col("char_type") == "П",
             F.col("balance_out") - F.col("debet_amount") + F.col("credit_amount")
        ).otherwise(F.col("balance_out"))
    )

    # Возврат с правильной on_date
    accounts = accounts.select('account_rk', 'balance_out', 'balance_out_rub')\
        .withColumn('on_date', F.lit(on_date))
print(f"on_date = {on_date}, prev_date = {prev_date_str}")
accounts.show()

on_date = 2018-01-01, prev_date = 31.12.2017
+----------+-----------+---------------+----------+
|account_rk|balance_out|balance_out_rub|   on_date|
+----------+-----------+---------------+----------+
|  36237725|        0.0|            0.0|2018-01-01|
|     24656|        0.0|            0.0|2018-01-01|
|  18849846|        0.0|            0.0|2018-01-01|
|   1972647|        0.0|            0.0|2018-01-01|
|  34157174|        0.0|            0.0|2018-01-01|
|  48829156|        0.0|            0.0|2018-01-01|
|     13905|        0.0|            0.0|2018-01-01|
|     17244|        0.0|            0.0|2018-01-01|
|  34156787|        0.0|            0.0|2018-01-01|
|     17132|        0.0|            0.0|2018-01-01|
|     13560|        0.0|            0.0|2018-01-01|
|     17439|        0.0|            0.0|2018-01-01|
|     17434|        0.0|            0.0|2018-01-01|
|     13630|        0.0|            0.0|2018-01-01|
| 277937699|        0.0|            0.0|2018-01-01|
|     13906|        0.0|            0.0|2018-01-01|
|     14136|        0.0|            0.0|2018-01-01|
|     13904|        0.0|            0.0|2018-01-01|
|  34157147|        0.0|            0.0|2018-01-01|
|     14138|        0.0|            0.0|2018-01-01|
+----------+-----------+---------------+----------+
only showing top 20 rows

In [20]:
spark.table("dm.dm_account_balance_f") \
    .filter("on_date = '2018-01-01'") \
    .select("account_rk", "balance_out") \
    .orderBy("balance_out", ascending=False) \
    .show()

+----------+-----------+
|account_rk|balance_out|
+----------+-----------+
|  36237725| 0.00000000|
|     24656| 0.00000000|
|  18849846| 0.00000000|
|   1972647| 0.00000000|
|  34157174| 0.00000000|
|  48829156| 0.00000000|
|     13905| 0.00000000|
|     17244| 0.00000000|
|  34156787| 0.00000000|
|     17132| 0.00000000|
|     13560| 0.00000000|
|     17439| 0.00000000|
|     17434| 0.00000000|
|     13630| 0.00000000|
| 277937699| 0.00000000|
|     13906| 0.00000000|
|     14136| 0.00000000|
|     13904| 0.00000000|
|  34157147| 0.00000000|
|     14138| 0.00000000|
+----------+-----------+
only showing top 20 rows